apiVersion: v1
kind: Service
metadata:
  name: springbootapp-port
spec:
  selector:
    app: springbootapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: springbootapp-port 
  type: NodePort
